FROM debian:10-slim

LABEL org.opencontainers.image.source https://github.com/frankier/finnvocabcollect

RUN apt-get update && \
    apt-get install -y \
      rsync git build-essential \
      python3 python3-dev python3-pip && \
    rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --upgrade \
    pip==20.2.4 \
    setuptools==50.3.2 \
    poetry==1.1.4 \
    poetry-core==1.0.0 \
    hypercorn

RUN ln -sf /usr/bin/python3.7 /usr/bin/python

USER nobody

WORKDIR /opt/finnvocabcollect

RUN mkdir -p /opt/finnvocabcollect
COPY selfassess/pyproject.toml selfassess/poetry.lock ./

USER root

RUN poetry export \
      --without-hashes > requirements.txt && \
    python3 -m pip install -r requirements.txt && \
    rm requirements.txt && \
    rm -rf /root/.cache

RUN echo "/selfassess" > \
    /usr/local/lib/python3.7/dist-packages/selfassess.pth

USER nobody

COPY selfassess ./

EXPOSE 8080
CMD ["hypercorn", "--insecure-bind", "0.0.0.0:8080", "--workers", "2", "selfassess.app:app"]
