"""Add miniexam tables

Revision ID: 1cd043e6c268
Revises: 
Create Date: 2021-08-26 09:41:05.325234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cd043e6c268'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('miniexam_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('miniexam_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('miniexam_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('miniexam_slot_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('response', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['miniexam_slot_id'], ['miniexam_slot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('miniexam_response')
    op.drop_table('miniexam_slot')
    # ### end Alembic commands ###
