"""non null a bunch of stuff

Revision ID: 6889fea58ea5
Revises: 8bdb3878ea0a
Create Date: 2021-09-18 13:45:04.522335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6889fea58ea5'
down_revision = '8bdb3878ea0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miniexam_response', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('response_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('miniexam_slot', schema=None) as batch_op:
        batch_op.alter_column('miniexam_order',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.alter_column('accept_deadline',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('complete_deadline',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('presentation', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('response_slot', schema=None) as batch_op:
        batch_op.alter_column('response_order',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('session_log_entry', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_log_entry', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('response_slot', schema=None) as batch_op:
        batch_op.alter_column('response_order',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('presentation', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.alter_column('complete_deadline',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('accept_deadline',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('miniexam_slot', schema=None) as batch_op:
        batch_op.alter_column('miniexam_order',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('miniexam_response', schema=None) as batch_op:
        batch_op.alter_column('response_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
