"""Add timestamp to session log entry

Revision ID: 6e460f174a15
Revises: c934a4a23707
Create Date: 2021-09-16 09:11:16.350098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e460f174a15'
down_revision = 'c934a4a23707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miniexam_response', schema=None) as batch_op:
        batch_op.alter_column('miniexam_slot_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('miniexam_slot', schema=None) as batch_op:
        batch_op.alter_column('participant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('word_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('presentation', schema=None) as batch_op:
        batch_op.alter_column('response_slot_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.alter_column('response_slot_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('response_slot', schema=None) as batch_op:
        batch_op.alter_column('participant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('word_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('session_log_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.alter_column('participant_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_log_entry', schema=None) as batch_op:
        batch_op.alter_column('participant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('response_slot', schema=None) as batch_op:
        batch_op.alter_column('word_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('participant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.alter_column('response_slot_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('presentation', schema=None) as batch_op:
        batch_op.alter_column('response_slot_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('miniexam_slot', schema=None) as batch_op:
        batch_op.alter_column('word_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('participant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('miniexam_response', schema=None) as batch_op:
        batch_op.alter_column('miniexam_slot_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
