"""add indexes

Revision ID: 7cd0a93ad2f5
Revises: 8b0e16095ba9
Create Date: 2021-10-05 10:34:48.723324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd0a93ad2f5'
down_revision = '8b0e16095ba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miniexam_response', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_miniexam_response_miniexam_slot_id'), ['miniexam_slot_id'], unique=False)

    with op.batch_alter_table('miniexam_slot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_miniexam_slot_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_miniexam_slot_word_id'), ['word_id'], unique=False)

    with op.batch_alter_table('participant_language', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participant_language_participant_id'), ['participant_id'], unique=False)

    with op.batch_alter_table('participant_response_language', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participant_response_language_participant_id'), ['participant_id'], unique=False)

    with op.batch_alter_table('presentation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presentation_response_slot_id'), ['response_slot_id'], unique=False)

    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_response_slot_id'), ['response_slot_id'], unique=False)

    with op.batch_alter_table('response_slot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_slot_participant_id'), ['participant_id'], unique=False)

    with op.batch_alter_table('session_log_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_log_entry_participant_id'), ['participant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_log_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_log_entry_participant_id'))

    with op.batch_alter_table('response_slot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_response_slot_participant_id'))

    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_response_response_slot_id'))

    with op.batch_alter_table('presentation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presentation_response_slot_id'))

    with op.batch_alter_table('participant_response_language', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participant_response_language_participant_id'))

    with op.batch_alter_table('participant_language', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participant_language_participant_id'))

    with op.batch_alter_table('miniexam_slot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_miniexam_slot_word_id'))
        batch_op.drop_index(batch_op.f('ix_miniexam_slot_participant_id'))

    with op.batch_alter_table('miniexam_response', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_miniexam_response_miniexam_slot_id'))

    # ### end Alembic commands ###
