"""added some accept flags

Revision ID: 85f1687b929c
Revises: 1cd043e6c268
Create Date: 2021-08-26 12:28:23.293889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f1687b929c'
down_revision = '1cd043e6c268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('selfassess_accept_date', sa.DateTime(), nullable=True))
    op.add_column('participant', sa.Column('miniexam_accept_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'miniexam_accept_date')
    op.drop_column('participant', 'selfassess_accept_date')
    # ### end Alembic commands ###
