"""add some fields to miniexam response table

Revision ID: c934a4a23707
Revises: 85f1687b929c
Create Date: 2021-08-26 15:08:16.312612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c934a4a23707'
down_revision = '85f1687b929c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miniexam_response', sa.Column('response_lang', sa.Enum('en', 'hu', 'ru', name='miniexamresponselanguage'), nullable=True))
    op.add_column('miniexam_response', sa.Column('response_type', sa.Enum('trans_defn', 'topic', 'donotknow', name='miniexamresponsetype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('miniexam_response', 'response_type')
    op.drop_column('miniexam_response', 'response_lang')
    # ### end Alembic commands ###
