"""add years in finland

Revision ID: cde958d20c94
Revises: ad2fd89406df
Create Date: 2021-09-28 10:11:12.731412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cde958d20c94'
down_revision = 'ad2fd89406df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lived_in_finland', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_column('lived_in_finland')

    # ### end Alembic commands ###
