"""add mark to miniexam response

Revision ID: df60f067baca
Revises: dd3d26ffb422
Create Date: 2021-09-17 18:09:37.585918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df60f067baca'
down_revision = 'dd3d26ffb422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miniexam_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mark', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miniexam_response', schema=None) as batch_op:
        batch_op.drop_column('mark')

    # ### end Alembic commands ###
